FROM prom/prometheus:v3.5.0 AS upstream

FROM scratch

COPY --from=upstream /bin/prometheus /bin/prometheus
COPY --from=upstream --chown=65534:65534 /prometheus /prometheus
COPY prometheus.yml /etc/prometheus/prometheus.yml

USER 65534:65534
ENTRYPOINT ["/bin/prometheus"]
CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]
